version: "3.8"

networks:
  loqui-network-dev:

volumes:
  loqui-data:
    name: loqui-data 

services:
  loqui-mongodb:
    container_name: loqui-mongodb
    image: mongo:4.2
    restart: always
    command: mongod --quiet --logpath /dev/null 
    env_file: 
      - ./engine/.env
    ports:
      - $MONGO_PORT:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PWD
      - MONGO_INITDB_DATABASE=$MONGO_DB_NAME
    networks:
      - loqui-network-dev
    volumes:
      - loqui-data:/data/db

  loqui-api:
    build:
      context: ./engine/
      dockerfile: ./Dockerfile.dev
    container_name: loqui-api
    env_file: .env
    ports:
      - 4000:4000
      - 9229:9229
    environment:
      - MONGO_DB_NAME=$MONGO_DB_NAME
      - MONGO_DB_USER=$MONGO_DB_USER
      - MONGO_PWD=$MONGO_PWD
      - MONGO_PORT=27017
      - MONGO_HOST=loqui-mongodb
    volumes:
      - type: bind
        source: ./engine/
        target: /app
    networks:
      - loqui-network-dev
    depends_on:
      - loqui-mongodb

  loquistudio:
    build:
      context: ./cms/
      dockerfile: ./Dockerfile
    container_name: loqui-studio
    ports:
      - 3000:3000
      - 9230:9229
    environment:
      - LOQUI_API=http://loqui-api:4000/v1
    volumes:
      - type: bind
        source: ./cms/
        target: /app
    networks:
      - loqui-network-dev
    depends_on:
      - loqui-mongodb