FROM golang
WORKDIR /app
RUN go get github.com/go-delve/delve/cmd/dlv
EXPOSE 4000 40000
COPY . .
RUN go mod download
RUN go build -gcflags="all=-N -l" -o /server
CMD ["dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/server"]
