// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"loquigo/engine/src/adapters/transport/http"
	"loquigo/engine/src/core/modules/contextmanager"
	"loquigo/engine/src/core/modules/dialogmanager"
	"loquigo/engine/src/core/modules/eventmanager"
	"loquigo/engine/src/core/modules/templatepool"
	"loquigo/engine/src/infrastructure"
	"loquigo/engine/src/infrastructure/database/mongo"
	"loquigo/engine/src/infrastructure/database/mongo/repositories"
)

// Injectors from wire.go:

func InitializeEvent(db mongo.MongoDB) (infrastructure.Server, error) {
	httpClient := infrastructure.NewHttpClient()
	sendMessageService := eventmanager.NewSendMessageService(httpClient)
	templatePoolService := templatepool.NewTemplatePoolService()
	userContextRepository := repositories.NewUserContextRepo(db)
	findContextService := contextmanager.NewFindContextService(userContextRepository)
	runDialogService := dialogmanager.NewRunDialogService(templatePoolService, findContextService)
	chatService := eventmanager.NewChatService(sendMessageService, runDialogService)
	chatController := adapters.NewChatController(chatService)
	server := infrastructure.NewServer(chatController)
	return server, nil
}
